name = "telega"
version = "0.2.0"
description = "Gleam Telegram Bot Library"
licences = ["Apache-2.0"]
repository = { type = "github", user = "bondiano", repo = "telega" }
links = [
    { title = "Issues", href = "https://github.com/bondiano/telega/issues" },
    { title = "Examples", href = "https://github.com/bondiano/telega/tree/master/examples"}
]

gleam = "~> 1.3.0"
target = "erlang"

[dependencies]
gleam_stdlib = "~> 0.39"
logging = "~> 1.0"
gleam_http = "~> 3.6"
gleam_httpc = "~> 2.2"
wisp = "~> 0.14"
gleam_json = "~> 1.0"
gleam_erlang = "~> 0.25"
gleam_otp = "~> 0.10"

[dev-dependencies]
gleeunit = "~> 1.0"
mockth = "0.3.2"
