name = "telega"
version = "0.0.5"
description = "Gleam Telegram Bot Library"
licences = ["Apache-2.0"]
repository = { type = "github", user = "bondiano", repo = "telega" }
links = [
    { title = "Issues", href = "https://github.com/bondiano/telega/issues" },
]

gleam = ">= 1.0.0"
target = "erlang"

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
logging = "~> 1.0"
gleam_http = "~> 3.6"
gleam_httpc = "~> 2.2"
wisp = "~> 0.12"
gleam_json = "~> 1.0"
gleam_erlang = "~> 0.25"

[dev-dependencies]
gleeunit = "~> 1.0"
mockth = "0.3.2"
