name = "telega"
version = "0.0.3"
description = "Gleam Telegram Bot Library"
licences = ["Apache-2.0"]
repository = { type = "github", user = "bondiano", repo = "telega" }

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
logging = "~> 1.0"
gleam_http = "~> 3.6"
gleam_httpc = "~> 2.2"
wisp = "~> 0.12"
gleam_json = "~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
