name = "bot"
version = "1.0.0"
description = "A Telega Session example"

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
mist = "~> 1.2.0"
gleam_erlang = "~> 0.25"
wisp = "~> 0.14"
dotenv_gleam = "1.0.5"
telega = { path = "../.." }
carpenter = "~> 0.3.1"

[dev-dependencies]
gleeunit = "~> 1.0"
