name: check

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.0"
          gleam-version: "1.4.0"
          rebar3-version: "3.23.0"
      - name: Install Dependencies
        run: gleam deps download
      - name: Test
        run: gleam test
      - name: Check Format
        run: gleam format --check src test
